---
title: "ChatGPT Output"
author: "Fabian Aiolfi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("stargazer")
library("knitr")
library("here")
opts_chunk$set(root.dir = here())

source("01-2_load_parl_data.R")
source("02_clean_data.R")
source("04_post_processing.R")
```

# Display output
```{r echo=FALSE, results = 'asis'}
query_3_pts
view_1 <- chatgpt_output_df %>%
  filter(query_type == "query_3_pts") %>% 
  select(-query_type)
kable(view_1, format = "html", row.names = FALSE)
```

```{r echo=FALSE, results = 'asis'}
query_1_sent
view_2 <- chatgpt_output_df %>%
  filter(query_type == "query_1_sent") %>% 
  select(-query_type)
kable(view_2, format = "html", row.names = FALSE)
```

```{r echo=FALSE, results = 'asis'}
query_central_stmnt
view_3 <- chatgpt_output_df %>%
  filter(query_type == "query_central_stmnt") %>% 
  select(-query_type)
kable(view_3, format = "html", row.names = FALSE)
```

```{r echo=FALSE, results = 'asis'}
query_3_keywords
view_4 <- chatgpt_output_df %>%
  filter(query_type == "query_3_keywords") %>% 
  select(-query_type)
kable(view_4, format = "html", row.names = FALSE)
```

